### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by haimin777** [natureyoo/Hemodialysis#1]
Hello, I'm researching for accurate prediction of concentration of K & Na during dialysys process. I find that you do a great work in this field. Could you share a Hemodialysis dataset from SNU ? Thank you.
P.S.
my email is alexhaimin@gmail.com

**Comment by natureyoo** [comment]
Hi, thank you for your interest. We're sorry that we can't release SNU's dataset.

**Comment by haimin777** [comment]
Ok, thank you for answer)

**Comment by haimin777** [comment]
+
